[package]
name = "bpcalc"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.33.0"
egui = "0.33.0"
palette = "0.7.6"

[profile.release]
opt-level = "z"
lto = "fat"         # More aggressive LTO
codegen-units = 1
strip = true
panic = "abort"